In [4]:
import torch 
import numpy as np 
import time 
from torch.nn import functional as F
device = device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [5]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()
elapsed_time = end_time - start_time 
print(f"{elapsed_time:.8f}")

0.00009155


In [7]:
torch_rand1 = torch.rand(100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100)
np_rand2 = torch.rand(100, 100, 100)

start_time = time.time()

rand = torch.matmul(torch_rand1, torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.dot(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}") 

0.00027657


C:\Users\Quoc Anh\AppData\Local\Temp\ipykernel_53468\928754288.py:18: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  rand = np.dot(np_rand1, np_rand2)


4.24768376


In [5]:
import torch.nn as nn 
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias= False)
print(linear(sample))

tensor([ 3.7010,  5.6028, -6.7236], grad_fn=<SqueezeBackward4>)


In [7]:
import torch.nn.functional as F
tensor1 = torch.tensor([2., 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.2119, 0.2119, 0.5761])


In [12]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b  = torch.tensor([[7,8,9],[10,11,12]])
#print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [14]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.8680, 0.8176, 0.6637, 0.9091, 0.4159],
         [0.0917, 0.9822, 0.2168, 0.7054, 0.0550],
         [0.3477, 0.8431, 0.1907, 0.6223, 0.3415]],

        [[0.6555, 0.6112, 0.0865, 0.7390, 0.7075],
         [0.2574, 0.8845, 0.4565, 0.7715, 0.8821],
         [0.4132, 0.1325, 0.6875, 0.3514, 0.1252]]])


In [5]:
x = torch.tensor([-0.05], dtype=torch.float32)
print(F.sigmoid(x))

tensor([0.4875])
